In [1]:
import numpy as np


In [2]:
np.random.binomial(1, 0.5)

0

In [3]:
np.random.binomial(1, 0.5, 100)

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1])

In [4]:
np.random.binomial(100, 0.5)

46

In [5]:
2 ** 100

1267650600228229401496703205376

In [6]:
N = 3
total_no = 0
while N > 0:
    total_no = total_no + 1
    tosses = np.random.binomial(1, 0.5, 10)
    if tosses.sum() == 5:
        print(tosses)
        N = N - 1
print(f'Total generated: {total_no}')

[0 1 1 0 1 1 0 0 0 1]
[1 0 0 0 1 1 0 1 0 1]
[0 1 1 1 0 0 0 1 1 0]
Total generated: 26


In [7]:
#########################################

# KM Practice - Data Science Bookcamp

In [8]:
sample_space = {'Heads', 'Tails'}

In [9]:
probability_heads = 1 / len(sample_space)

In [10]:
print(f'Probability of choosing heads is {probability_heads}')

Probability of choosing heads is 0.5


In [11]:
def is_heads_or_tails(outcome): return outcome in {'Heads', 'Tails'}

In [12]:
is_heads_or_tails('Tails')

True

In [13]:
def is_neither(outcome): return not is_heads_or_tails(outcome)

In [14]:
is_neither('Heads')

False

In [15]:
def is_heads(outcome): return outcome == 'Heads'
def is_tails(outcome): return outcome == 'Tails'

In [16]:
is_heads('Heads')

True

In [17]:
def get_matching_event(event_condition, sample_space):
    return set([outcome for outcome in sample_space if event_condition(outcome)])

In [18]:
event_conditions = [is_heads_or_tails, is_heads, is_tails, is_neither]

In [19]:
for event_condition in event_conditions:
    print(f"Event Condition: {event_condition.__name__}")
    event = get_matching_event(event_condition, sample_space)
    print(f'Event: {event}\n')

Event Condition: is_heads_or_tails
Event: {'Heads', 'Tails'}

Event Condition: is_heads
Event: {'Heads'}

Event Condition: is_tails
Event: {'Tails'}

Event Condition: is_neither
Event: set()



In [20]:
def compute_probability(event_condition, generic_sample_space):
    event = get_matching_event(event_condition, generic_sample_space)
    return len(event) / len(generic_sample_space)

In [21]:
for event_condition in event_conditions:
    prob = compute_probability(event_condition, sample_space)
    name = event_condition.__name__
    print(f"Probability of event arising from '{name}' is {prob}")

Probability of event arising from 'is_heads_or_tails' is 1.0
Probability of event arising from 'is_heads' is 0.5
Probability of event arising from 'is_tails' is 0.5
Probability of event arising from 'is_neither' is 0.0


# Analyzing a biased coin


In [22]:
weighted_sample_space = {'Heads': 4, 'Tails': 1}

In [23]:
sample_space_size = sum(weighted_sample_space.values())
assert sample_space_size == 5

In [24]:
event = get_matching_event(is_heads_or_tails, weighted_sample_space)
event_size = sum(weighted_sample_space[outcome] for outcome in event)
assert event_size == 5

In [25]:
def compute_event_probability(event_condition, generic_sample_space):
    event = get_matching_event(event_condition, generic_sample_space)
    if type(generic_sample_space) == type(set()):
        return len(event) / len(generic_sample_space.values)
    event_size = sum(generic_sample_space[outcome] for outcome in event)
    return event_size / sum(generic_sample_space.values())

In [26]:
for event_condition in event_conditions:
    prob = compute_event_probability(event_condition, weighted_sample_space)
    name = event_condition.__name__
    print(f"Probability of event arising from '{name}' is {prob}")

Probability of event arising from 'is_heads_or_tails' is 1.0
Probability of event arising from 'is_heads' is 0.8
Probability of event arising from 'is_tails' is 0.2
Probability of event arising from 'is_neither' is 0.0


************* Binomial Distribution rough work **********

In [27]:
((0.45 ** 9 + 0.55 ** (15-9))

0.028437321267578138

In [30]:
import math
math.factorial(15)

1307674368000

In [39]:
math.factorial(15) / (math.factorial(15-9) * math.factorial(9)) * (0.45 ** 9 * (1 - 0.45) ** (15 - 9))

0.10483175170017132

In [36]:
5005 * (0.45 ** 9 + (1 - 0.45) ** (15 - 9))

142.32879294422858

In [40]:
math.factorial(80) / (math.factorial(80-30) * math.factorial(30)) * (0.35 ** 30 * (1 - 0.35) ** (80 - 30))

0.0823572691795739